apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::492737776546:role/federal-ps-eks-stack-EKSNodeInstanceRole-DOHAnliptvVW
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::492737776546:role/AWSReservedSSO_nonprod-administrator_6bbd747b1460f5f4
      username: sso-admin
  mapUsers: |
    - userarn: arn:aws:iam::492737776546:user/nbargovic
      username: nbargovic
      groups:
      - system:masters
    - userarn: arn:aws:iam::492737776546:user/naraja
      username: naraja
      groups:
      - system:masters
    - userarn: arn:aws:iam::492737776546:user/cstevenson
      username: cstevenson
      groups:
      - system:masters      
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system

